net.Receive("FMenu", function()
    local frame = vgui.Create("DFrame")
    frame:SetSize(500, 500)
    frame:SetPos(ScrW() / 2 - 250, ScrH() / 2 - 250)
    frame:SetTitle("Lockdown Menu")
    frame:SetDraggable(false)
    frame:ShowCloseButton(true)
    frame:MakePopup()
end)